mybatch_old_111/apps/account/urls.py
from django.conf.urls import url

from .views import LoginClass
from .views import logout
from .views import RegisterClass

urlpatterns = [    
    # url(r'^login/$', LoginClass, name='login'),
    url(r'^login/$', LoginClass.as_view(), name='login'),
    url(r'^logout/', logout, name = 'logout'),
    url(r'^register/$', RegisterClass, name='register'),
   
    
]

mybatch_old_111/mybatch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import home
from .views import dashboard

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('apps.account.urls', namespace="account")),
    url(r'^config/', include('apps.config.urls', namespace="config")),   
    url(r'^$', home, name = "home"),
    # url(r'^dashboard/', dashboard, name = "dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mybatch_old_111/templates/base_home.html
{% load staticfiles %}

<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}" />
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>MyBatch</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
</head>

<body>
    <nav class="navbar navbar-primary navbar-transparent navbar-absolute">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">My Batch | Electronic Batch Record</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/">
                            <i class="material-icons">dashboard</i> App
                        </a>
                    </li>
                    <li class="">
                        <a href="register.html">
                            <i class="material-icons">person_add</i> Registrarse
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'account:login' %}">
                            <i class="material-icons">fingerprint</i> Ingresar
                        </a>
                    </li>                    
                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper wrapper-full-page">
        {% block wrapper %}

        {% endblock wrapper %}
    </div>
            
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/material.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{% static 'js/moment.min.js' %}"></script>
<!--  Charts Plugin -->
<script src="{% static 'js/chartist.min.js' %}"></script>
<!--  Plugin for the Wizard -->
<script src="{% static 'js/jquery.bootstrap-wizard.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'js/bootstrap-notify.js' %}"></script>
<!-- DateTimePicker Plugin -->
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<!-- Vector Map plugin -->
<script src="{% static 'js/jquery-jvectormap.js' %}"></script>
<!-- Sliders Plugin -->
<script src="{% static 'js/nouislider.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js"></script>
<!-- Select Plugin -->
<script src="{% static 'js/jquery.select-bootstrap.js' %}"></script>
<!--  DataTables.net Plugin    -->
<script src="{% static 'js/jquery.datatables.js' %}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{% static 'js/sweetalert2.js' %}"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static 'js/jasny-bootstrap.min.js' %}"></script>
<!--  Full Calendar Plugin    -->
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
<!-- TagsInput Plugin -->
<script src="{% static 'js/jquery.tagsinput.js' %}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'js/material-dashboard.js' %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'js/demo.js' %}"></script>
<script type="text/javascript">
    $().ready(function() {
        demo.checkFullPageBackgroundImage();

        setTimeout(function() {
            // after 1000 ms we add the class animated to the login/register card
            $('.card').removeClass('card-hidden');
        }, 700)
    });
</script>

</html>