mybatch_old_111/apps/config/urls.py
from django.conf.urls import url
from .views import EquipmentCreateClass
from .views import EquipmentListClass
from .views import EquipmentUpdateClass
from .views import EquipmentDetailClass
from .views import equipment_index
from .views import EquipmentGeneratePdf
from .views import EquipmentDelete


from .views import MaterialCreateClass
from .views import MaterialListClass
from .views import MaterialUpdateClass
from .views import MaterialDetailClass
# from .views import Material_index
from .views import MaterialDelete
from .views import MaterialGeneratePdf
from .views import Material_index


urlpatterns = [

	# url(r'^crear/$', EquipoCreate, name='equipo_create'),
	url(r'^equipment/index', equipment_index, name = "equipment_index"),
	url(r'^equipment/create', EquipmentCreateClass.as_view(), name = "equipment_create"),
	url(r'^equipment/list', EquipmentListClass.as_view(), name = "equipment_list"),
	url(r'^equipment/edit/(?P<pk>\d+)/$', EquipmentUpdateClass.as_view(), name='equipment_edit'),
	url(r'^equipment/detail/(?P<pk>\d+)/$', EquipmentDetailClass.as_view(), name='equipment_detail'),
	url(r'^equipment/delete/(?P<pk>\d+)/$',EquipmentDelete.as_view(), name='equipment_delete'),
	url(r'^equipment/pdf_list/$', EquipmentGeneratePdf.as_view(), name='equipment_pdf_list'),

	url(r'^material/index', Material_index, name = "material_index"),
    url(r'^material/list', MaterialListClass.as_view(), name = "material_list"),
	url(r'^material/edit//(?P<pk>\d+)/$', MaterialUpdateClass.as_view(), name = "material_edit"),
	url(r'^material/create', MaterialCreateClass.as_view(), name = "material_create"),
	url(r'^material/pdf_list/$', MaterialGeneratePdf.as_view(), name='material_pdf_list'),
	url(r'^material/detail/(?P<pk>\d+)/$', MaterialDetailClass.as_view(), name='material_detail'),
	url(r'^material/delete/(?P<pk>\d+)/$',MaterialDelete.as_view(), name='material_delete'),
	url(r'^material/pdf_list/$', MaterialGeneratePdf.as_view(), name='material_pdf_list'),

]

mybatch_old_111/mybatch/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import home
from .views import dashboard

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('apps.account.urls', namespace="account")),
    url(r'^config/', include('apps.config.urls', namespace="config")),   
    url(r'^$', home, name = "home"),
    # url(r'^dashboard/', dashboard, name = "dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartbatch/apps/config/urls.py
from django.conf.urls import url



urlpatterns = [



]

smartbatch/smartbatch/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from .views import home
from .views import dashboard


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = "home"),
    path('dashboard/', dashboard , name='dashboard'),
    path('account/', include('apps.account.urls'), name='account'),
    path('config/', include('apps.config.urls'), name='config'),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartbatch/apps/config/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import models

# Create your models here.

from apps.account.models import Empresa


class Proveedor(models.Model):
	empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
	nombre_proveedor = models.CharField(max_length=150)

	def __str__(self):
		return self.nombre_proveedor

class Fabricante(models.Model):
	empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
	nombre_fabricante = models.CharField(max_length=150)

	def __str__(self):
		return self.nombre_fabricante

class Equipo(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
    codigo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=150)
    fabricante  = models.ForeignKey(Fabricante, on_delete = models.CASCADE)
    capacidad_maxima= models.DecimalField(max_digits=5, decimal_places=2)
    capacidad_minima= models.DecimalField(max_digits=5, decimal_places=2)
    UNIDAD_CHOICES = (
        ('TON', 'Toneladas'),
        ('L','Litros'),
        ('KG','Kilogramos'),
        ('G','Gramos'),
        ('LB','Libras'),
    )
    unidad = models.CharField(
    max_length=20,
    choices=UNIDAD_CHOICES,
    )
    fecha_calibracion = models.DateField(blank=True, null=True)
    calibrable = models.BooleanField()

    CALIFICADO_CHOICES = (
        ('SI', 'SI'),
        ('NO','NO'),
        ('NA','NO APLICA'),
    )
    calificado = models.CharField(
    max_length=15,
    choices=CALIFICADO_CHOICES,	
    )

    ESTADO_CHOICES = (
        ('MANTENIMIENTO', 'En mantenimiento'),
        ('ACTIVO','Activo'),
        ('INACTIVO','Inactivo'),
    )
    estado = models.CharField(
    max_length=20,
    choices=ESTADO_CHOICES,

    )
    otras_caracteristicas = models.TextField(blank=True, null=True)
    ficha_tecnica = models.FileField(upload_to='pdf/config/equipo', blank=True, null = True,)


    def __str__(self):
        return self.codigo


class Material(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
    TIPO_CHOICES = (
        ('MATERIA_PRIMA', 'materia prima'),
        ('MATERIAL_EMPAQUE','material de empaque'),
    )
    tipo = models.CharField(
        max_length=30,
        choices=TIPO_CHOICES,
    )
    codigo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=150)
    UNIDAD_CHOICES = (
        ('TON', 'Toneladas'),
        ('L','Litros'),
        ('KG','Kilogramos'),
        ('G','Gramos'),
        ('LB','Libras'),
        ('ADIMENSIONAL','adimensional')
    )
    unidad = models.CharField(
        max_length=20,
        choices=UNIDAD_CHOICES,
    )
    fabricante  = models.ForeignKey(Fabricante, on_delete = models.CASCADE)
    proveedor = models.ManyToManyField(Proveedor)
    pureza_maxima= models.DecimalField(max_digits=5, decimal_places=2)
    pureza_minima= models.DecimalField(max_digits=5, decimal_places=2)	
    ficha_seguridad = models.FileField(upload_to='pdf/config/material/ficha_seguridad', blank=True)

def __str__(self):
    return self.codigo

mybatch_old_111/apps/config/forms.py
from django import forms

from .models import Equipo
from .models import Material

class EquipoForm(forms.ModelForm):
	pass

# 	class Meta:
# 		model = Equipo
# 		exclude = ["empresa"]

# 		fields = [
# 			'codigo',
# 			'descripcion',
# 			'marca',
# 			'capacidad_maxima_de_operacion',
# 			'unidad',
# 			'ficha_tecnica',
# 			'fecha_calibracion',
# 			'estado',
# 			'foto1',
# 			'foto2',
# 			'foto3',
# 		]

# 		labels = {
# 			'codigo':'Codigo del Equipo *',
# 			'descripcion':'Descripcion del Equipo *',
# 			'marca':'Marca *',
# 			'capacidad_maxima_de_operacion':'Capacidad Maxima de Operacion *',
# 			'unidad':'Unidad de Medida *',
# 			'ficha_tecnica':'Ficha Tecnica *',
# 			'fecha_calibracion':'Fecha de Calibracion',
# 			'estado':'Estado *',
# 			'foto1':'Foto1',
# 			'foto2':'Foto2',
# 			'foto3':'Foto3',
# 		}

# 		widgets = {
# 			'codigo':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
# 			'descripcion':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
# 			'marca':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
# 			'capacidad_maxima_de_operacion':forms.NumberInput(attrs={'class':'form-control','required':'true'}),
# 			'unidad':forms.Select(attrs={'class':'selectpicker','data-style':'btn btn-info btn-sm btn-round', 'required':'true'}),
# 			'ficha_tecnica':forms.FileInput(attrs={}),
# 			'fecha_calibracion':forms.DateInput(attrs={'class':'form-control datepicker'}),
# 			'estado':forms.Select(attrs={'class':'selectpicker','data-style':'btn btn-info btn-sm btn-round', 'required':'true'}),
# 			'foto1':forms.FileInput(attrs={'class':''}),
# 			'foto2':forms.FileInput(attrs={'class':''}),
# 			'foto3':forms.FileInput(attrs={'class':''}),
# 		}

class MaterialForm(forms.ModelForm):
	class Meta:
		model = Material
		exclude = ["empresa"]

		fields = [
			'codigo',
			'descripcion',
			'proveedor',
			'fabricante',
			'unidad_UMB',
			'ficha_tecnica',
			'concentracion',
			'N_de_lote_fabricante',
			'fecha_de_vencimiento',
			'estado',
			'certificado_calidad',
			'costo_UMB',
		]

		labels = {
			'codigo' : 'Codigo del Material *',
			'descripcion' : 'Descripcion del Material *',
			'proveedor' : 'Proveedor del Material *',
			'fabricante' : 'Fabricante del Material *',
			'unidad_UMB' : 'Unidad de Medida Basica UMB *',
			'ficha_tecnica' : 'Ficha Tecnica del Material',
			'concentracion' : 'Concentracion del Material',
			'N_de_lote_fabricante' : 'Numero de Lote del Fabricante',
			'fecha_de_vencimiento' : 'Fecha de Vencimiento',
			'estado' : 'Estado',
			'certificado_calidad' : 'Certificado de Calidad',
			'costo_UMB' : 'Costo de la Unidad de Medida Basica *',
		}

		widgets = {
			'codigo':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
			'descripcion':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
			# 'proveedor'
			# 'fabricante',
			'unidad_UMB':forms.Select(attrs={'class':'selectpicker','data-style':'btn btn-info btn-sm btn-round', 'required':'true'}),
			'ficha_tecnica':forms.FileInput(attrs={}),
			'concentracion':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
			'N_de_lote_fabricante':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
			'fecha_de_vencimiento':forms.DateInput(attrs={'class':'form-control datepicker'}),
			'estado':forms.Select(attrs={'class':'selectpicker','data-style':'btn btn-info btn-sm btn-round', 'required':'true'}),
			'certificado_calidad':forms.FileInput(attrs={}),
			'costo_UMB':forms.TextInput(attrs={'class':'form-control','type':'text','required':'true'}),
		}

mybatch_old_111/apps/config/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

from django.shortcuts import render

from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import View

from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect
from django.http import HttpResponse


from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

from .models import Equipo
from .models import Material

from apps.account.models import Empresa

from mybatch.utils import render_to_pdf

from .forms import EquipoForm
from .forms import MaterialForm
from django.utils import timezone


def equipment_index(request):
    return render(request, 'config/equipment/equipment_index.html', {})


class EquipmentCreateClass(LoginRequiredMixin, CreateView):
	login_url = 'account:login'
	model = Equipo
	template_name = 'config/equipment/equipment_create.html'
	form_class = EquipoForm
	success_url = reverse_lazy('config:equipment_list')
	success_message = 'equipo registrado de forma exitosa'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.empresa = Empresa.objects.get(id=self.request.user.cliente.empresa.id)  # use your own profile here
		self.object.save()
		messages.success(self.request,self.success_message)
		return HttpResponseRedirect( self.get_success_url() )

class EquipmentListClass(LoginRequiredMixin, ListView):
	login_url = 'account:login'
	model = Equipo
	template_name = 'config/equipment/equipment_list.html'

	def get_queryset(self):
		return Equipo.objects.filter(empresa=self.request.user.cliente.empresa.id)



class EquipmentUpdateClass(LoginRequiredMixin, UpdateView):
	login_url = 'account:login'
	model = Equipo
	form_class = EquipoForm
	template_name = 'config/equipment/equipment_edit.html'
	success_url = reverse_lazy('config:equipment_list')
	success_message = 'equipo actualizado de forma exitosa'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.empresa = Empresa.objects.get(id=self.request.user.cliente.empresa.id)  # use your own profile here
		self.object.save()
		messages.success(self.request,self.success_message)
		return HttpResponseRedirect( self.get_success_url() )

class EquipmentDetailClass(LoginRequiredMixin, DetailView):
	login_url = 'account:login'
	model = Equipo
	template_name = 'config/equipment/equipment_detail.html'


class EquipmentDelete(LoginRequiredMixin,DeleteView):
	login_url = 'account:login'
	model = Equipo
	template_name = 'config/equipment/equipment_delete.html'
	success_url = reverse_lazy('config:equipment_list')



class EquipmentGeneratePdf(LoginRequiredMixin, ListView):
     login_url = 'account:login'
     model = Equipo
     def get(self, request, *args, **kwargs):
         data = {
             'user':self.request.user,
             'date_time':timezone.now(),
             'object_list':Equipo.objects.filter(empresa=self.request.user.cliente.empresa.id),
         }
         pdf = render_to_pdf('config/equipment/equipment_list_pdf.html', data)
         return HttpResponse(pdf, content_type='application/pdf')


# +++++++++++++++++++ material +++++++++++++++++++++++++++++++++++++++++++++


def Material_index(request):
	return render(request, 'config/material/material_index.html', {})


class MaterialCreateClass(LoginRequiredMixin, CreateView):
    login_url = 'account:login'
    model = Material
    template_name = 'config/material/material_create.html'
    form_class = MaterialForm
    success_url = reverse_lazy('config:material_list')
    success_message = 'material registrado de forma exitosa'

    def form_valid(self, form):          
        self.object = form.save(commit=False)          
        self.object.empresa = Empresa.objects.get(id=self.request.user.cliente.empresa.id)  # use your own profile here
        self.object.save()
        form.save_m2m()#this line is adde because the many 2 many filed is not saved
        messages.success(self.request,self.success_message)
        return HttpResponseRedirect( self.get_success_url() )

class MaterialListClass(LoginRequiredMixin, ListView):
    login_url = 'account:login'
    model = Material
    template_name = 'config/material/material_list.html'

    def get_queryset(self):
        return Material.objects.filter(empresa=self.request.user.cliente.empresa.id)

class MaterialUpdateClass(LoginRequiredMixin, UpdateView):
    pass

# class MaterialUpdateClass(LoginRequiredMixin, UpdateView):
#     login_url = 'account:login'
#     model = Equipo
#     form_class = EquipoForm
#     template_name = 'config/material/material_edit.html'
#     success_url = reverse_lazy('config:material_list')
#     success_message = 'equipo actualizado de forma exitosa'

#     def form_valid(self, form):
#         self.object = form.save(commit=False)
#         self.object.empresa = Empresa.objects.get(id=self.request.user.cliente.empresa.id)  # use your own profile here
#         self.object.save()
#         messages.success(self.request,self.success_message)
#         return HttpResponseRedirect( self.get_success_url() )


class MaterialDetailClass(LoginRequiredMixin, DetailView):
    login_url = 'account:login'
    model = Material
    template_name = 'config/material/material_detail.html'

class MaterialDelete(LoginRequiredMixin,DeleteView):
    login_url = 'account:login'
    model = Material
    template_name = 'config/material/material_delete.html'
    success_url = reverse_lazy('config:material_list')


class MaterialGeneratePdf(LoginRequiredMixin, ListView):
     login_url = 'account:login'
     model = Material
     def get(self, request, *args, **kwargs):
         data = {
             'user':self.request.user,
             'date_time':timezone.now(),
             'object_list':Material.objects.filter(empresa=self.request.user.cliente.empresa.id),
         }
         pdf = render_to_pdf('config/material/material_list_pdf.html', data)
         return HttpResponse(pdf, content_type='application/pdf')

smartbatch/apps/config/views.py
from django.shortcuts import render

# Create your views here.

templates/config/equipement/equipement_delete.html
{% extends 'config/equipement/equipement_index.html'%}
{% load staticfiles %}

{% block container_fluid %}

<div class="row">
    <div class="col-md-12">
        <div class="card">            

            <div class="card-content text-center">
                <form method="post">
                    {% csrf_token %}
                    <h3>Seguro que Desea eliminar el equipo:</h3>
                    <h4><b>{{object.codigo}} {{object.descripcion}}</b>, del registro</h4>
                    <button class="btn btn-danger">eliminar</button>
                    <a class="btn btn-default" href="{% url 'config:equipement_edit' object.id %}">cancelar</a>                     
                </form>
            </div>
                 
        </div>      
    </div>

</div>         

   
    

{% endblock container_fluid %} 
    

{% block aditional_scripts %}



{% endblock aditional_scripts %}

    

    

templates/config/equipement/equipement_index.html
{% extends 'base_app.html'%}
{% load staticfiles %}

{% block config_equipo %}
    <li class="active">
        <a data-toggle="collapse" href="#configuracion">
            <i class="material-icons">settings</i>
            <p>Configuracion
                <b class="caret"></b>
            </p>
        </a>
        <div class="collapse in" id="configuracion">
            <ul class="nav">
                <li class="active">
                    <a href="{% url 'config:equipment_list' %}">Equipos</a>
                </li>                       
            </ul>
        </div>
    </li>
{% endblock config_equipo %} 


{% block container_fluid %}

<div class="row">

    <div class="col-md-12">
          
    </div>
</div>
{% endblock container_fluid %} 

templates/config/equipement/equipement_list.html
{% extends 'config/equipement/equipement_index.html'%}
{% load staticfiles %}

{% block aditional-css %}

<style>

    .row-icon {
      visibility: hidden;
    }
    tr:hover .row-icon{
      visibility: visible;
    }


#myImg {
    border-radius: 5px;
    cursor: pointer;
    transition: 0.3s;
}

#myImg:hover {opacity: 0.7;}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    padding-top: 100px; /* Location of the box */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.9); /* Black w/ opacity */
}

/* Modal Content (image) */
.modal-content {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
}

/* Caption of Modal Image */
#caption {
    margin: auto;
    display: block;
    width: 80%;
    max-width: 700px;
    text-align: center;
    color: #ccc;
    padding: 10px 0;
    height: 150px;
}

/* Add Animation */
.modal-content, #caption {    
    -webkit-animation-name: zoom;
    -webkit-animation-duration: 0.6s;
    animation-name: zoom;
    animation-duration: 0.6s;
}

@-webkit-keyframes zoom {
    from {-webkit-transform:scale(0)} 
    to {-webkit-transform:scale(1)}
}

@keyframes zoom {
    from {transform:scale(0)} 
    to {transform:scale(1)}
}

/* The Close Button */
.close {
    position: absolute;
    top: 15px;
    right: 35px;
    color: #f1f1f1;
    font-size: 40px;
    font-weight: bold;
    transition: 0.3s;
}

.close:hover,
.close:focus {
    color: #bbb;
    text-decoration: none;
    cursor: pointer;
}

/* 100% Image Width on Smaller Screens */
@media only screen and (max-width: 700px){
    .modal-content {
        width: 100%;
    }
}

</style>
        
{% endblock aditional-css %}


{% block container_fluid %}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-icon" data-background-color="blue">
                <i class="material-icons">assignment</i>
            </div>            
            <div class="card-content">
                <h4 class="card-title">lista de Equipos</h4>
                
                <h4 id="messagetag" >{% if messages %}{% for message in messages  %}{{message}}{% endfor %}{% endif %}</h4>
                
                <div class="toolbar">                 
                    <button onclick="location.href='{% url 'config:equipment_create' %}'" class="btn btn-danger btn-just-icon btn-round pull-right">
                        <i class="material-icons">add</i>                        
                    </button>  
                </div>
                <div class="material-datatables">
                    <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                        <thead>
                            <tr>
                                <td></td>                                
                                <td><b>Codigo</b></td>
                                <td><b>Descripcion</b></td>
                                <td><b>Marca</b></td>
                                <td><b>Capacidad unidad</b></td>
                                <td><b>ficha</b></td>
                                <td><b>calibracion</b></td>
                                <td><b>Estado</b></td>
                                <td><b>foto1</b></td>
                                <td><b>foto2</b></td>
                                <td><b>foto3</b></td>
                                
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <td></td>                                
                                <td>Codigo</td>
                                <td>Descripcion</td>
                                <td>Marca</td>
                                <td>Capacidad unidad</td>
                                <td>ficha</td>
                                <td>calibracion</td>
                                <td>Estado</td>
                                <td>foto1</td>
                                <td>foto2</td> 
                                <td>foto3</td>                      
                                
                            </tr>
                        </tfoot>
                        <tbody>
                            {% if object_list %}
                                {% for  equipo in object_list%}
                                    <tr>
                                        <td> 
                                            <span class="row-icon">                                   
                                                <a href="#">
                                                    <i class="material-icons">create</i>
                                                </a>
                                            </span>                        
                                            
                                        </td>                               
                                        <td><a href="{% url 'config:equipement_edit' equipo.id%}">{{ equipo.codigo }}</a></td>
                                        <td><a href="{% url 'config:equipement_edit' equipo.id%}">{{ equipo.descripcion }}</a></td>
                                        <td><a href="{% url 'config:equipement_edit' equipo.id%}">{{ equipo.marca }}</a></td>
                                        <td><a href="{% url 'config:equipement_edit' equipo.id%}">{{ equipo.capacidad_maxima_de_operacion}} {{equipo.unidad}}</a></td>                           
                                        <td>
                                            {% if equipo.ficha_tecnica %}
                                                <a href="{{ equipo.ficha_tecnica.url }}" target="_blank">
                                                    <span><i class="material-icons">description</i>
                                                    </span>
                                                </a> 
                                            {% else %}
                                                <span><i class="material-icons">clear</i></span>                                          
                                            {% endif %}

                                        </td>
                                        <td>{{ equipo.fecha_calibracion }}</td>
                                        <td>
                                            <a href="{% url 'config:equipement_edit' equipo.id%}">
                                             {% if equipo.estado == "A" %}
                                                Activo                                                 
                                             {% elif equipo.estado == "I" %}
                                                Inactivo
                                             {% elif equipo.estado == "M"  %}
                                                Mantenimiento
                                             {% else %}
                                                ----                                            
                                             {% endif %}

                                            </a>
                                        </td>
                                        <td class="icono-imagen"> 
                                            <a href="#">
                                            {% if equipo.foto1 %}
                                                <span class="image-view">
                                                    <i class="material-icons">image</i>                                             
                                                     <img class="imagen" id="myImg" src="{{ equipo.foto1.url }}" width="10" height="10"> 
                                                </span> 
                                            {% else %}
                                                <span class="image-view">
                                                   <i class="material-icons">visibility_off</i>
                                                </span>
                                            {% endif %}               
                                            </a>                                           
                                        </td>
                                         <td class="icono-imagen"> 
                                            <a href="#">
                                            {% if equipo.foto2 %}
                                                <span class="image-view">
                                                    <i class="material-icons">image</i>                                             
                                                     <img class="imagen" id="myImg" src="{{ equipo.foto2.url }}" width="10" height="10"> 
                                                </span> 
                                            {% else %}
                                                <span class="image-view">
                                                   <i class="material-icons">visibility_off</i>
                                                </span>
                                            {% endif %}               
                                            </a>                                           
                                        </td>
                                        <td class="icono-imagen"> 
                                            <a href="#">
                                            {% if equipo.foto3 %}
                                                <span class="image-view">
                                                    <i class="material-icons">image</i>                                             
                                                     <img class="imagen" id="myImg" src="{{ equipo.foto3.url }}" width="10" height="10"> 
                                                </span> 
                                            {% else %}
                                                <span class="image-view">
                                                   <i class="material-icons">visibility_off</i>
                                                </span>
                                            {% endif %}               
                                            </a>                                           
                                        </td>                                    
                                    </tr>
                                {% endfor %}                                
                            {% else %}
                                <h1>No a creado ningun equipo</h1>                          
                            {% endif %}                            
                        </tbody>
                    </table>            

                     
                </div>
            </div>            
        </div>      
    </div>
</div>  

<div id="myModal" class="modal">
  <span class="close">&times;</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

{% endblock container_fluid %} 
    

{% block aditional_scripts %}

<script>
// Get the modal
var modal = document.getElementById('myModal');
$( ".imagen").hide();
$( ".image-view" ).click(function(){
    var modal = document.getElementById('myModal');
    // Get the image and insert it inside the modal - use its "alt" text as a caption    
    var modalImg = document.getElementById("img01");    
    console.log($(this).find('img').attr('src'));
    modal.style.display = "block";
    modalImg.src = $(this).find('img').attr('src');
    });

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() { 
    modal.style.display = "none";
}
</script>

<script> 
    let messagetag = document.getElementById("messagetag").innerHTML;
    if(messagetag != ""){
        swal({
                title: "Genial!",
                text: messagetag,
                buttonsStyling: false,
                confirmButtonClass: "btn btn-success btn-fill",
                type: "success"
            });
    }
</script>



{% endblock aditional_scripts %}

    