smartbatch/apps/account/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name="account"

urlpatterns = [   
   
    path('login/', views.LoginClass.as_view(), name='login'),
    path('logout/', views.logout, name = 'logout'),
    path('register/', views.register, name='register'),
   
    
]

smartbatch/apps/config/urls.py
from django.conf.urls import url



urlpatterns = [



]

smartbatch/smartbatch/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.urls import include, path
from django.conf.urls.static import static
from .views import home
from .views import dashboard


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name = "home"),
    path('dashboard/', dashboard , name='dashboard'),
    path('account/', include('apps.account.urls'), name='account'),
    path('config/', include('apps.config.urls'), name='config'),
   
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

smartbatch/apps/account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class Empresa(models.Model):
	nombre = models.CharField(max_length=100)
	pais_CHOICES = (
	    ('Colombia', 'Colombia'),
	    ('Mexico','Mexico'),	      
	)
	pais = models.CharField(		
		max_length=20,
		choices=pais_CHOICES,
		) 
	nit = models.CharField(max_length=100, blank=True, null=True)
	ciudad = models.CharField(max_length=50, blank=True, null=True)
	direccion = models.CharField(max_length=50, blank=True, null=True)
	telefono = models.CharField(max_length=50, blank=True, null=True)
	sitioweb = models.URLField(blank=True, null=True)
	mail = models.EmailField(blank=True, null=True)
	logo = models.ImageField(upload_to='img/account/empresa', blank=True, null=True)# tamanio de 178 px de ancho por 51 alto

	def __str__(self):
			return self.nombre

class Cliente(models.Model):
	usuario = models.OneToOneField(User, on_delete =  models.CASCADE)
	tipo_usuario_CHOICES = (
	    ('Administrador', 'administrador'),
	    ('Limitado','Limitado'),	      
	)
	tipo_usuario = models.CharField(		
		max_length=20,
		choices=tipo_usuario_CHOICES,
		)
	empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)

	def __str__(self):
		return self.usuario.username

smartbatch/apps/config/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import models

# Create your models here.

from apps.account.models import Empresa


class Proveedor(models.Model):
	empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
	nombre_proveedor = models.CharField(max_length=150)

	def __str__(self):
		return self.nombre_proveedor

class Fabricante(models.Model):
	empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
	nombre_fabricante = models.CharField(max_length=150)

	def __str__(self):
		return self.nombre_fabricante

class Equipo(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
    codigo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=150)
    fabricante  = models.ForeignKey(Fabricante, on_delete = models.CASCADE)
    capacidad_maxima= models.DecimalField(max_digits=5, decimal_places=2)
    capacidad_minima= models.DecimalField(max_digits=5, decimal_places=2)
    UNIDAD_CHOICES = (
        ('TON', 'Toneladas'),
        ('L','Litros'),
        ('KG','Kilogramos'),
        ('G','Gramos'),
        ('LB','Libras'),
    )
    unidad = models.CharField(
    max_length=20,
    choices=UNIDAD_CHOICES,
    )
    fecha_calibracion = models.DateField(blank=True, null=True)
    calibrable = models.BooleanField()

    CALIFICADO_CHOICES = (
        ('SI', 'SI'),
        ('NO','NO'),
        ('NA','NO APLICA'),
    )
    calificado = models.CharField(
    max_length=15,
    choices=CALIFICADO_CHOICES,	
    )

    ESTADO_CHOICES = (
        ('MANTENIMIENTO', 'En mantenimiento'),
        ('ACTIVO','Activo'),
        ('INACTIVO','Inactivo'),
    )
    estado = models.CharField(
    max_length=20,
    choices=ESTADO_CHOICES,

    )
    otras_caracteristicas = models.TextField(blank=True, null=True)
    ficha_tecnica = models.FileField(upload_to='pdf/config/equipo', blank=True, null = True,)


    def __str__(self):
        return self.codigo


class Material(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete = models.CASCADE)
    TIPO_CHOICES = (
        ('MATERIA_PRIMA', 'materia prima'),
        ('MATERIAL_EMPAQUE','material de empaque'),
    )
    tipo = models.CharField(
        max_length=30,
        choices=TIPO_CHOICES,
    )
    codigo = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=150)
    UNIDAD_CHOICES = (
        ('TON', 'Toneladas'),
        ('L','Litros'),
        ('KG','Kilogramos'),
        ('G','Gramos'),
        ('LB','Libras'),
        ('ADIMENSIONAL','adimensional')
    )
    unidad = models.CharField(
        max_length=20,
        choices=UNIDAD_CHOICES,
    )
    fabricante  = models.ForeignKey(Fabricante, on_delete = models.CASCADE)
    proveedor = models.ManyToManyField(Proveedor)
    pureza_maxima= models.DecimalField(max_digits=5, decimal_places=2)
    pureza_minima= models.DecimalField(max_digits=5, decimal_places=2)	
    ficha_seguridad = models.FileField(upload_to='pdf/config/material/ficha_seguridad', blank=True)

def __str__(self):
    return self.codigo

smartbatch/apps/account/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User


class LoginUserForm(forms.Form):
	username = forms.CharField(max_length=20, label = 'Usuario')
	password = forms.CharField(max_length= 20,label = 'Contraseña', widget=forms.PasswordInput())

	def __init__(self, *args, **kwargs):#utilizo el constructr de la clase form
		super(LoginUserForm, self).__init__(*args, **kwargs)#le digo que no sobreescriba el constructor sino que haga lo que ya hacia
		self.fields['username'].widget.attrs.update( {'id' : 'username_login' , 'class':'form-control'} )
		self.fields['password'].widget.attrs.update( {'id' : 'password_login' , 'class':'form-control'} )

smartbatch/apps/account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as logout_django

from django.shortcuts import redirect
from django.views.generic import View
from django.http import HttpResponse
from .forms import LoginUserForm



class LoginClass(View):
	form = LoginUserForm()
	message = None 
	template = 'account/login.html'

	def get(self, request, *args, **kwargs):
		if request.user.is_authenticated:			
			return redirect('dashboard')
		return render(request, self.template, self.get_contexto())

	def post(self, request, *args, **kwargs):
		username_post = request.POST['username']
		password_post = request.POST['password']
		user = authenticate(username = username_post, password = password_post)

		if user is not None:
			login_django(request,user)
			return redirect('dashboard')		
		else:
			self.message = "usuario o pasword incorrecto"
		return render(request, self.template, self.get_contexto())

	def get_contexto(self):
		return{'form':self.form, 'message':self.message}


@login_required(login_url = 'account:login')
def logout(request):
	logout_django(request)
	return redirect('home')

def register(request):
	return render(request, 'account/register.html')

smartbatch/apps/config/views.py
from django.shortcuts import render

# Create your views here.

smartbatch/smartbatch/views.py
from django.shortcuts import render

from django.shortcuts import redirect

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required



def home(request):
	# if request.user.is_authenticated():
	# 	return redirect('dashboard')

	return render(request, 'pricing.html', {})

def error_404(request):
	return render(request, 'error_404.html', {})	

@login_required(login_url = 'account:login')
def dashboard(request):
	return render(request, 'dashboard.html')

smartbatch/templates/base_app.html
{% load staticfiles %}
<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png'%}" />
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>My Batch</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css" rel="stylesheet' %}" />
    <!--  CSS for project     -->
    <link href="{% static 'css/app.css" rel="stylesheet' %}" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />

    {% block aditional-css %}

    {% endblock aditional-css %}
</head>

<body>
    <div class="wrapper">
        <div class="sidebar" data-active-color="blue" data-background-color="black" data-image="{% static 'img/sidebar-1.jpg' %}">
            <!--
        Tip 1: You can change the color of active element of the sidebar using: data-active-color="purple | blue | green | orange | red | rose"
        Tip 2: you can also add an image using data-image tag
        Tip 3: you can change the color of the sidebar with data-background-color="white | black"
    -->
            <div class="logo">
                <a href="/" class="simple-text">
                    My Batch
                </a>
            </div>
            <div class="logo logo-mini">
                <a href="/" class="simple-text">
                    MB
                </a>
            </div>
            <div class="sidebar-wrapper">
                <div class="user">
                    <div class="photo">
                        <img src="{% static 'img/placeholder.jpg' %}" />
                    </div>
                    <div class="info">
                        <a data-toggle="collapse" href="#collapseExample" class="collapsed">
                            {{ user.username}}
                            <b class="caret"></b>
                        </a>
                        <div class="collapse" id="collapseExample">
                            <ul class="nav">
                                <li>
                                    <a href="#">Editar Perfil</a>
                                </li>
                                <li>
                                    
                                    {% comment  %}
                                    <a href="{% url 'account:logout'%}">Salir</a>
                                    {% endcomment %}
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <ul class="nav">

                    {% block Dashboard %}
                        <li>
                            <a href="/">
                                <i class="material-icons">dashboard</i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                    {% endblock Dashboard %}

                    {% block config %}
                        <li>
                            <a data-toggle="collapse" href="#configuracion">
                                <i class="material-icons">settings</i>
                                <p>Configuracion
                                    <b class="caret"></b>
                                </p>
                            </a>
                            <div class="collapse" id="configuracion">
                                <ul class="nav">
                                    <li>
                                        {% comment "" %}
                                        <a href="{% url 'config:equipment_list' %}">Equipos</a>
                                        {% endcomment %}                                        
                                    </li>
                                    <li>
                                        {% comment "" %}
                                        <a href="{% url 'config:material_list' %}">Material</a>
                                        {% endcomment %}                                        
                                    </li>
                                </ul>
                            </div>
                        </li>
                    {% endblock config %}


                </ul>
            </div>
        </div>
        <div class="main-panel">
            <nav class="navbar navbar-transparent navbar-absolute">
                <div class="container-fluid">
                    <div class="navbar-minimize">
                        <button id="minimizeSidebar" class="btn btn-round btn-white btn-fill btn-just-icon">
                            <i class="material-icons visible-on-sidebar-regular">more_vert</i>
                            <i class="material-icons visible-on-sidebar-mini">view_list</i>
                        </button>
                    </div>
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">{{user.cliente.empresa}}</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">notifications</i>
                                    <span class="notification">5</span>
                                    <p class="hidden-lg hidden-md">
                                        Notifications
                                        <b class="caret"></b>
                                    </p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="#">Terminar area de preparacion</a>
                                    </li>
                                    <li>
                                        <a href="#">Tarea1</a>
                                    </li>
                                    <li>
                                        <a href="#">Tarea2</a>
                                    </li>
                                    <li>
                                        <a href="#">otra notificacion</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="material-icons">person</i>
                                    <p class="hidden-lg hidden-md">Profile</p>
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        
                                        <a href="{% url 'account:logout' %}">Salir</a>
                                                                              
                                    </li>
                                </ul>
                            </li>
                            <li class="separator hidden-lg hidden-md"></li>
                        </ul>

                        <!--
                        <form class="navbar-form navbar-right" role="search">
                            <div class="form-group form-search is-empty">
                                <input type="text" class="form-control" placeholder="Buscar">
                                <span class="material-input"></span>
                            </div>
                            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                <i class="material-icons">search</i>
                                <div class="ripple-container"></div>
                            </button>
                        </form>

                         -->
                    </div>
                </div>
            </nav>
            <div class="content">
                <div class="container-fluid">
                    {% block container_fluid %}

                    {% endblock container_fluid %}

                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="/">
                                    Inicio
                                </a>
                            </li>
                            <li>
                                <a href="http://www.cieltechno.com">
                                    Compañia
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Blog
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="http://www.cieltechno.com">CielTechno®</a>, Tecnologia farmaceutica a su alcance
                    </p>
                </div>
            </footer>
        </div>
    </div>
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/material.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{% static 'js/moment.min.js' %}"></script>
<!--  Charts Plugin -->
<script src="{% static 'js/chartist.min.js' %}"></script>
<!--  Plugin for the Wizard -->
<script src="{% static 'js/jquery.bootstrap-wizard.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'js/bootstrap-notify.js' %}"></script>
<!-- DateTimePicker Plugin -->
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<!-- Vector Map plugin -->
<script src="{% static 'js/jquery-jvectormap.js' %}"></script>
<!-- Sliders Plugin -->
<script src="{% static 'js/nouislider.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<!-- <script src="https://maps.googleapis.com/maps/api/js"></script>   -->

<!-- Select Plugin -->
<script src="{% static 'js/jquery.select-bootstrap.js' %}"></script>
<!--  DataTables.net Plugin    -->
<script src="{% static 'js/jquery.datatables.js' %}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{% static 'js/sweetalert2.js' %}"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static 'js/jasny-bootstrap.min.js' %}"></script>
<!--  Full Calendar Plugin    -->
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
<!-- TagsInput Plugin -->
<script src="{% static 'js/jquery.tagsinput.js' %}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'js/material-dashboard.js' %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'js/demo.js' %}"></script>

{% block aditional_scripts %}

<!-- <script type="text/javascript">
    $(document).ready(function() {

        // Javascript method's body can be found in assets/js/demos.js
        demo.initDashboardPageCharts();

        demo.initVectorMap();
    });
</script> -->


{% endblock aditional_scripts %}


</html>

smartbatch/templates/base_home.html
{% load staticfiles %}

<!doctype html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/apple-icon.png' %}" />
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <title>MyBatch</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <!--  Material Dashboard CSS    -->
    <link href="{% static 'css/material-dashboard.css' %}" rel="stylesheet" />
    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'css/demo.css' %}" rel="stylesheet" />
    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons" />
</head>

<body>
    <nav class="navbar navbar-primary navbar-transparent navbar-absolute">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">SmartBatch | Electronic Batch Record</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                   
                    <li class="">
                        <a href="{% url 'account:register' %}">
                            <i class="material-icons">person_add</i> Registrarse
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'account:login' %}">
                            <i class="material-icons">fingerprint</i> Ingresar
                        </a>
                    </li>                    
                </ul>
            </div>
        </div>
    </nav>
    <div class="wrapper wrapper-full-page">
        {% block wrapper %}

        {% endblock wrapper %}
    </div>
            
</body>
<!--   Core JS Files   -->
<script src="{% static 'js/jquery-3.1.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/material.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/perfect-scrollbar.jquery.min.js' %}" type="text/javascript"></script>
<!-- Forms Validations Plugin -->
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{% static 'js/moment.min.js' %}"></script>
<!--  Charts Plugin -->
<script src="{% static 'js/chartist.min.js' %}"></script>
<!--  Plugin for the Wizard -->
<script src="{% static 'js/jquery.bootstrap-wizard.js' %}"></script>
<!--  Notifications Plugin    -->
<script src="{% static 'js/bootstrap-notify.js' %}"></script>
<!-- DateTimePicker Plugin -->
<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>
<!-- Vector Map plugin -->
<script src="{% static 'js/jquery-jvectormap.js' %}"></script>
<!-- Sliders Plugin -->
<script src="{% static 'js/nouislider.min.js' %}"></script>
<!--  Google Maps Plugin    -->
<script src="https://maps.googleapis.com/maps/api/js"></script>
<!-- Select Plugin -->
<script src="{% static 'js/jquery.select-bootstrap.js' %}"></script>
<!--  DataTables.net Plugin    -->
<script src="{% static 'js/jquery.datatables.js' %}"></script>
<!-- Sweet Alert 2 plugin -->
<script src="{% static 'js/sweetalert2.js' %}"></script>
<!--	Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
<script src="{% static 'js/jasny-bootstrap.min.js' %}"></script>
<!--  Full Calendar Plugin    -->
<script src="{% static 'js/fullcalendar.min.js' %}"></script>
<!-- TagsInput Plugin -->
<script src="{% static 'js/jquery.tagsinput.js' %}"></script>
<!-- Material Dashboard javascript methods -->
<script src="{% static 'js/material-dashboard.js' %}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{% static 'js/demo.js' %}"></script>
<script type="text/javascript">
    $().ready(function() {
        demo.checkFullPageBackgroundImage();

        setTimeout(function() {
            // after 1000 ms we add the class animated to the login/register card
            $('.card').removeClass('card-hidden');
        }, 700)
    });
</script>

</html>

smartbatch/templates/config/material/material_list_pdf.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Reporte de Materiales {{user.cliente.empresa}}</title>
        <style type="text/css">

               @page {
                    size: a4 portrait;
                   @frame header_frame {           /* Static Frame */
                       -pdf-frame-content: header_content;
                       left: 50pt; width: 512pt; top: 50pt; height: 40pt;
                   }
                   @frame content_frame {          /* Content Frame */
                       left: 50pt; width: 512pt; top: 90pt; height: 632pt;
                   }
                   @frame footer_frame {           /* Another static Frame */
                       -pdf-frame-content: footer_content;
                       left: 50pt; width: 512pt; top: 772pt; height: 20pt;
                   }
               }
                        
           body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: right !important;
                /*margin-left: 40%;*/
            }

        </style>
    </head>
    <body>

        <!-- Content for Static Frame 'header_frame' -->
       <div id="header_content">Reporte generado por <a href="smartbatch">smartbatch.com</a></div>
        
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Reporte de Materiales de manofactura y calidad</p>
            </div>
        <div>
            <div class='details'>
                Generado por:{{user.first_name}} {{user.last_name}} <br/>
                Empresa: {{user.cliente.empresa}}<br/>
                Fecha y hora: {{date_time}}
                <hr class='hrItem' />
            </div>

            {% if object_list %}
                {% for  material in object_list%}
                    <b>Codigo:</b> {{material.codigo}}<br/>
                    <b>Descripcion:</b> {{material.descripcion}}<br/>

                    <b>Proveedor:</b> 
                    {% for proveedor in material.proveedor.all  %}
                        {{proveedor.nombre_proveedor}} |                        
                    {% endfor %}                    
                    <br>

                    <b>fabricante:</b> 
                    {% for fabricante in material.fabricante.all  %}
                        {{fabricante.nombre_fabricante}} |                        
                    {% endfor %}                    
                    <br>

                    <b>Unidad de Medida Basica UMB:</b> {{material.get_unidad_UMB_display}}<br/>

                    <b>ficha tecnica:</b>
                        {% if material.ficha_tecnica %}
                            <a href="{{ material.ficha_tecnica.url }}" target="_blank">
                                <span>{{ material.ficha_tecnica.url }}</span>
                            </a> 
                        {% else %}
                            <span>no</span>                                          
                        {% endif %}

                    <br/>

                    <b>Concentracion:</b> {{material.concentracion}}<br/>

                    <b>Numero de lote del fabricante:</b> {{material.N_de_lote_fabricante}}<br/>
                    
                    <b>Fecha de Vencimiento:</b> {{material.fecha_de_vencimiento}}<br/>

                    <b>Estado:</b>
                    {{ material.get_estado_display}}                   
                    <br/>              



                    <b></b> <br>

                {% endfor %}        
            {% endif %}
               




       </div>
      
           <!-- Content for Static Frame 'footer_frame' -->
       <div id="footer_content">pagina <pdf:pagenumber>
           de <pdf:pagecount>  
           
       </div>

    </body>
</html>